wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1643146706
    t:
      1:
      - 15
      2:
      - 15
      3:
      - 2
      4: 3.8.12
      5: 0.12.9
      8:
      - 1
      - 5
